In [7]:
import pandas as pd
import os

In [9]:
folder = '../영화csv파일' # csv있는 폴더
csv_files = [file for file in os.listdir(folder) if file.endswith('.csv')]
dataframes = [pd.read_csv(os.path.join(folder, file)) for file in csv_files]
movie_df = pd.concat(dataframes, ignore_index=True)
movie_df.to_csv('../프로젝트저장csv/movie_df.csv', index=False, encoding='utf-8')
print(len(movie_df)) # 총 6043
movies = movie_df.copy()

6043

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6043 entries, 0 to 6042
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NO                    6043 non-null   int64
 1   MOVIE_NM              6043 non-null   object
 2   DRCTR_NM              5173 non-null   object
 3   MAKR_NM               2364 non-null   object
 4   INCME_CMPNY_NM        3197 non-null   object
 5   DISTB_CMPNY_NM        6043 non-null   object
 6   OPN_DE                6041 non-null   object
 7   MOVIE_TY_NM           6043 non-null   object
 8   MOVIE_STLE_NM         6043 non-null   object
 9   NLTY_NM               6043 non-null   object
 10  TOT_SCRN_CO           5638 non-null   object
 11  SALES_PRICE           2053 non-null   object
 12  VIEWNG_NMPR_CO        4188 non-null   object
 13  SEOUL_SALES_PRICE     2612 non-null   object
 14  SEOUL_VIEWNG_NMPR_CO  4548 non-null   object
 15  GENRE_NM              6029 non-null   object
 16  GRAD_NM               6043 non-null   object
 17  MOVIE_SDIV_NM         6043 non-null   object
dtypes: int64(1), object(17)
memory usage: 849.9+ KB

In [11]:
movies.head()

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
0,1,소울,피트 닥터,"월트 디즈니 픽쳐스,픽사 애니메이션 스튜디오",월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,20210120,개봉영화,장편,미국,2018,7936332910,875001,2578880980,275009,애니메이션,전체관람가,일반영화
1,2,극장판 귀멸의 칼날: 무한열차편,소토자키 하루오,NaN,에스엠지홀딩스 주식회사,워터홀컴퍼니(주),20210127,개봉영화,장편,일본,380,1820102670,206309,507360670,54677,애니메이션,15세이상관람가,일반영화
2,3,원더 우먼 1984,팻티 젠킨스,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20201223,개봉영화,장편,미국,2260,1445202000,155562,425776520,43999,액션,12세이상관람가,일반영화
3,4,세자매,이승원,(주)영화사 업,NaN,(주)리틀빅픽쳐스,20210127,개봉영화,장편,한국,569,354451240,42290,110117100,12825,드라마,15세이상관람가,독립/예술영화
4,5,명탐정 코난: 진홍의 수학여행,야마모토 야스이치로,NaN,(주)씨제이이엔엠,(주)씨제이이엔엠,20210127,개봉영화,장편,일본,532,316132440,38131,61262750,7166,애니메이션,12세이상관람가,일반영화